### ISSUE TITLE
did someone say cock

### ISSUE THREAD

**Issue by whitefox08** [MoistBaguette/KaukMod#1]
:eyes:

**Comment by MoistBaguette** [comment]
I'd just like to interject for moment. What you're refering to as cock, is in fact, Kauk/Mod, or as I've recently taken to calling it, Kauk plus Mod. Kauk is not a mod unto itself, but rather another free component of a fully functioning mod collection made useful by the Kauk corelibs, shell utilities and vital mod components comprising a full Mod Collection as defined by KAUK.

**Comment by whitefox08** [comment]
woh
